# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1
	verbosity: 5

key:
	name: "k1"
	algorithm: hmac-sha256
	secret: "K2tf3TRjvQkVCmJF3/Z9vA=="

key:
	name: "k2"
	algorithm: hmac-sha256
	secret: "K2tf3TRjvQkVCmJF3/Z9bA=="

zone:
	name: example.com.
	zonefile: tsig_del_axfr.zone
	request-xfr: 127.0.0.1@TESTNS_PORT k1
	allow-notify: 127.0.0.1/0 k1
	provide-xfr: 127.0.0.1/0 k1

remote-control:
	control-enable: yes
	control-interface: 127.0.0.1
	control-port: CONTROL_PORT
	server-key-file: "nsd_server.key"
	server-cert-file: "nsd_server.pem"
	control-key-file: "nsd_control.key"
	control-cert-file: "nsd_control.pem"

