.\"
.\" nsd-patch.8 -- nsd-patch manual
.\"
.\" Copyright (c) 2001-2006, NLnet Labs. All rights reserved.
.\"
.\" See LICENSE for the license.
.\"
.\"
.Dd @date@
.Os FreeBSD
.Dt nsd-patch 8
.Sh NAME
.Nm nsd-patch
.Nd NSD zone patcher version @version@.
.Sh SYNOPSIS
.Nm nsd-patch
.Op Fl c Ar configfile
.Op Fl f
.Op Fl h
.Op Fl l
.Op Fl x Ar difffile
.Sh DESCRIPTION
.Ic Nsd-patch
is the zone patcher for
.Xr nsd 8 .
It reads in the nsd database (nsd.db) and difffile (ixfr.db), and overwrites
the zone text files if they have been updated. Running this regularly
ensures that the difffile does not grow infinitely.
.Pp
The available options are:
.Bl -tag -width indent
.It Fl c Ar configfile
Read specified configfile instead of the default
.Pa /etc/nsd/nsd.conf .
.It Fl f
Forces writing zone files. Also zones that have not changed are written
back to their zone files.
.It Fl h
Print usage help information and exit.
.It Fl l
List the journal entries from the difffile. Does not write to zone files.
.It Fl x Ar difffile
Read specified difffile. Overrides the config file setting.
.El
.Sh FILES
.Bl -tag -width indent
.It Pa /var/db/nsd/nsd.db
default
.Ic NSD
database
.It Pa /etc/nsd/nsd.conf
default
.Ic NSD
configuration file
.El
.Sh SEE ALSO
.Xr nsd 8 ,
.Xr nsd.conf 5 ,
.Xr nsd-checkconf 8 ,
.Xr nsd-notify 8 ,
.Xr nsd-xfer 8 ,
.Xr nsdc 8
.Sh AUTHORS
.Ic NSD
was written by NLnet Labs and RIPE NCC joint team. Please see CREDITS file
in the distribution for further details.
