.TH "nsd-notify" "8" "1.0.2b1" "NLnet Labs" "nsd"
.SH "NAME"
.LP 
nsd\-notify \- program to send NOTIFY's to remote nameservers
.SH "SYNTAX"
.LP 
nsd\-notify \fI\-z\fP \fIzone\fP \fIservers\fP
.SH "DESCRIPTION"
.LP 
nsd\-notify is simple program to send NOTIFY's to remoter nameservers.
.br 
NSD is a complete implementation of an authoritative DNS nameserver.
.SH "OPTIONS"
.LP 
.TP 
\fB\-z zone\fR
specify zone to notify about
.TP 
\fBservers\fR
list of ip addresses of nameservers to send to.
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
nsd\-notify \-z foobar.cz 1.2.3.4
.SH "AUTHORS"
.LP 
NLnet Labs <info@nlnet.nl>
.SH "SEE ALSO"
.LP 
nsd(8) zonec(8)
