.ig
nsd.8 -- nsd manual

Copyright (c) 2001, 2002, 2003, NLnet Labs. All rights reserved.

This software is an open source.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

Neither the name of the NLNET LABS nor the names of its contributors may
be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
..
.Dd @date@
.Dt NSD 8 
.Sh NAME
nsd
.Nd Name Server Daemon (NSD) version @version@.
.Sh SYNOPSIS
.Nm nsd
.Op Fl 4
.Op Fl 6
.Op Fl a Ar ip-address
.Op Fl d 
.Op Fl f Ar database
.Op Fl h
.Op Fl i Ar identity
.Op Fl l Ar logfile
.Op Fl N Ar udp-servers
.Op Fl n Ar tcp-servers
.Op Fl p Ar port
.Op Fl s Ar secondss
.Op Fl t Ar chrootdir
.Op Fl u Ar username
.Op Fl v
.Op Fl X Ar plugin

.Sh DESCRIPTION
.Ic NSD
is a complete implementation of an authoritative DNS nameserver. Upon
startup
.Ic NSD
will read the database specified with -f
.Ar database
argument and put itself into background and answers queries on port 53
or a different port specified with -p
.Ar port
option.
The
.Ar database
must be generated beforehand with
.Xr zonec
(8).
By default NSD will bind to all local interfaces available. Use the -a
.Ar ip-address
option to specify a single particular interface address to be bound. If this option
is given more than once,
.Ic NSD
will bind its UDP sockets to all the specified ip-addresses separately and
use INADDR_ANY for the TCP socket.
.Pp
Normally
.Ic NSD
should be started with
.Xr nsdc 8
start
command invoked from a
.Em /etc/rc.d/nsd.sh
script or similar at the operating system startup.
.Pp
The available options are:
.Bl -tag -width indent

.It Fl 4
Only listen to IPv4 connections.

.It Fl 6
Only listen to IPv6 connections.

.It Fl a Ar ip-address
Listen to the specified
.Ar ip-address .
The 
.Ar ip-address
must be specified in numeric format (using the standard IPv4 or IPv6
notation).  This flag can be specified multiple times to listen to
multiple IP addresses.  If this flag is not specified NSD listens to
all IP addresses.

.It Fl d
Turn on debugging mode, do not fork, stay in the foreground.

.It Fl f Ar database
Use the specified
.Ar database
instead of the default of
.Em /etc/nsd/nsd.db .

.It Fl h
Print help information and exit.

.It Fl i Ar identity
Return the specified
.Ar identity
when asked for
.Em CH TXT ID.SERVER
(This option is used to determine which server is answering the queries
when they are multicast)
The default is the name returned by
.Xr gethostname 3 .

.It Fl l Ar logfile
Log messages to the specified 
.Ar logfile .
The default is to log to stderr and syslog.

.It Fl N Ar count
Start
.Ar count
UDP servers.  Starting more than a single UDP server is only useful on
machines with multiple CPUs and/or network adapters.

.It Fl n Ar count
Start
.Ar count
TCP servers.  This is also the maximum number of simultaneously
handled TCP connections.

.It Fl p Ar port
Answer the queries on the specified
.Ar port .
Normally this is port 53.

.It Fl s Ar seconds
Produce statistics dump every 
.Ar seconds
seconds.
This is equal to sending
.Em SIGILL
to the daemon periodically.

.It Fl t Ar chroot
specifies a directory to chroot to upon startup. This option requires you to
ensure that appropriate 
.Xr syslogd 8
socket (e.g.
.Ar chrootdir 
/dev/log) is available otherwise
.Ic NSD
won't produce any log output.

.It Fl u Ar username
Drop user and group privileges to those of
.Ar username
after binding the socket.
The
.Ar username
must one of: username, id, or id.gid.  For example: nsd, 80, or 80.80.

.It Fl v
Print the version number of NSD to standard error and exit.

.It Fl X Ar plugin
Load a
.Ar plugin .
The
.Ar plugin
argument must be of the form 
.Ar filename ,
or 
.Ar filename=argument .
The filename must specify an NSD plugin compiled as a shared object
(.so) file.  If the filename is not absolute the shared object is
searched for in the standard locations using
.Xr dlopen 3 .
If an argument is specified it is passed directly to the
initialization function of the plugin.

.El

.Pp
.Ic NSD
reacts to the following signals:
.Bl -tag -width indent
.It Dv SIGTERM
Stop answering queries, shutdown, and exit normally.
.It Dv SIGHUP
Reload the database.
.It Dv SIGILL
Dump BIND8-style statistics into the log. Ignored otherwise.
.El
.\" .Sh IMPLEMENTATION NOTES
.Sh FILES
.Bl -tag -width indent
.It Pa /etc/nsd/nsd.db
default
.Ic NSD
database
.It Pa /var/run/nsd.pid
the process id of the name server.
.El
.Sh DIAGNOSTICS
.Ic NSD
will log all the problems via the standard
.Xr syslog 8
.Em daemon
facility, unless the
.Ar -d
option is specified.
.Sh SEE ALSO
.Xr zonec 8 ,
.Xr nsdc 8
.Sh AUTHORS
.Ic NSD
was written by NLnet Labs and RIPE NCC joint team. Please see the
CREDITS file in the distribution for further details.
.Sh BUGS
.Ic NSD
will answer the queries erroneously if the
.Ar database
was not properly compiled with
.Xr zonec 8 .
Therefore problems with misconfigured master zone files or 
.Xr zonec 8
bugs may not be visible until the queries are actually answered
with
.Ic NSD .
