.\"
.\" $Id: nsdc.8,v 1.10 2003/07/07 09:29:25 erik Exp $
.\"
.\" nsdc.8 -- nsdc manual
.\"
.\" Alexis Yushin, <alexis@nlnetlabs.nl>
.\"
.\" Copyright (c) 2001, 2002, 2003, NLnet Labs. All rights reserved.
.\"
.\" This software is an open source.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" Redistributions of source code must retain the above copyright notice,
.\" this list of conditions and the following disclaimer.
.\"
.\" Redistributions in binary form must reproduce the above copyright notice,
.\" this list of conditions and the following disclaimer in the documentation
.\" and/or other materials provided with the distribution.
.\"
.\" Neither the name of the NLNET LABS nor the names of its contributors may
.\" be used to endorse or promote products derived from this software without
.\" specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd @date@
.Os FreeBSD
.Dt nsdc 8 
.Sh NAME
.Nm nsdc
.Nd Name Server Daemon (NSD) Control Script
.Sh SYNOPSIS
.Nm nsdc
.Ar start|stop|reload|rebuild|restart|running|update|notify
.Sh DESCRIPTION
.Ic Nsdc
is the shell script that used to control
.Xr nsd 8
and
.Xr zonec 8
from
.Ic NSD
distribution.
.Ic Nsdc
is also suitable to be linked into
.Pa /etc/rc.d
directory on
.Em BSD
like systems for automatic startup of
.Xr nsd 8
at the boot time.
.Pp
At every invokation
.Ic nsdc
will try to source
.Pa /etc/nsd/nsdc.conf
configuration file (shell script) where default configuration settings 
can be overwritten. An example of such configuration file is distributed
with the
.Ic NSD
package as
.Pa nsdc.conf.sample
.Pp
Possible
.Ic nsdc
applications are:
.Bl -tag -width indent
.It Ar start
Start
.Xr nsd 8
.It Ar stop
Shut down
.Xr nsd 8
by sending
.Em SIGTERM
to it.
.It Ar reload
Initiate
.Xr nsd 8
name space database reload by sending
.Em SIGHUP
.It rebuild
Rebuild the
.Xr nsd 8
database by invoking
.Xr zonec 8
with appropriate arguments.
.It Ar restart
Restart
.Xr nsdc 8
This equals to nsdc stop && nsdc start
.It Ar running
Check whether
.Xr nsd 8
is running. Returns error message and error code if it is not
running, and no message and zero error code otherwise.
.It Ar update
Updates all the slave zones which have
.Em master
keyword in
.Pa nsd.zones
file from its masters and invokes
.Em nsdc rebuild
and
.Em nsdc reload
if necessary.
.It Ar notify
Sends
.Em notify
message to all the masters for all the zones that have
.Em notify
keyword in
.Pa nsd.zones
file.
.El
.Pp
See the
.Pa README
file for detailed description of
.Pa nsd.zones
file format.
.Sh FILES
.Bl -tag -width indent
.It Pa /etc/nsd.zones
Default location of configuration file.
.It Pa /etc/nsd/nsd.db
default
.Ic NSD
database
.It Pa /var/run/nsd.pid
the process id of the name server.
.It Pa /etc/nsd/nsdc.conf
Optional configuration file for nsdc to overwrite default pathnames
and
.Ic NSD
flags.
.El
.Sh DIAGNOSTICS
.Ic Nsdc
will return zero return code if operation was successful and
an error message to standard output plus a non-zero return code
otherwise.
.Sh SEE ALSO
.Xr zonec 8
.Xr nsd 8
.Xr README
.Sh AUTHORS
.Ic NSD
was written by NLnet LABS and RIPE NCC joint team. Please see CREDITS file
in the distribution for further details.
.Sh BUGS
.Pa nsd.zones
syntax checking is almost nonexistent in
.Ic nsdc
erroneous lines are most likely to be ignored or will produce unexpected
results. There is no locking for
.Em nsdc rebuild
and
.Em nsdc update
operations so those should be used with caution.
.Pp
.Em nsdc
update with more than one master will give error messages and wont work
with tsig. To fix the problem one can comment out checking for tsig
file presence in
.Em nsdc.sh.in
