.\" @(#)nsdc.8 2002 
.TH nsdc 8  "20 Feb 2002"
.SH NAME
nsdc \- Name Server Daemon Control
.SH SYNOPSIS
.B nsdc
[ 
\fBstart\fR|\fBstop\fR|\fBreload\fR|\fBrunning\fR|\fBrebuild\fR|\fBrestart\fR
]

.SH DESCRIPTION
.B nsdc 
is a control tool for nsd(8) and zonec(8) and is part of
the \fBNSD\fP package written by NLnet Labs
in collaboration with RIPE NCC. \fBNSD\fP stands for
\fIn\fRame\fIs\fRerver \fId\fRaemon and provides
authoritative DNS information.
.br
Nsdc expects various files, like zonefiles
and database, to be in specific places, but as it is a simple
shell script it can easily be editted.

.SH OPTIONS
.TP
.B start
start \fInsd\fR.

.TP
.B stop
stop \fInsd\fR.

.TP
.B reload
reload the database \fInsd\fR is using.

.TP
.B running
check if \fInsd\fR is running.

.TP
.B rebuild
rebuild the zone database using \fIzonec\fR.

.TP
.B restart
restart \fInsd\fR.

.SH AUTHOR
\fInsd\fR is written by Alexis Yushin (NLnet Labs) with
valuable input and assistance from Jaap Akkerhuis (SIDN),
Daniel Karrenberg and Olaf Kolkman (RIPE-NCC), and Miek
Gieben, Erik Rozendaal, and Ted Lindgreen (NLnet Labs).

.SH "SEE ALSO"
.BR zonec (8),
.BR nsd (8).

.SH CODE STATUS
The current version, 1.0.0, has beta status. The latest
version can be retrieved from
.br
\fIhttp://www.nlnetlabs.nl/nsd/index.en.html\fR

.SH REPORTING BUGS
Please report bugs to nsd-bugs@nlnetlabs.nl.

.SH COPYRIGHT
Copyright NLnet Labs 2002, BSD License.
