.\" @(#)zonec.8 2002 
.TH zonec 8  "22 Feb 2002"
.SH NAME
zonec \- Zone Compiler
.SH SYNOPSIS
.B zonec
[ \fB\-d\fR ] [ \fB\-v\fR ] [ \fB\-f \fIdatabase\fR ]
.BI zone-list-file

.SH DESCRIPTION
.B zonec
is the Zone Compiler from the \fBNSD\fP package written by NLnet Labs
in collaboration with RIPE NCC. \fBNSD\fP stands for
\fIn\fRame\fIs\fRerver \fId\fRaemon and provides
authoritative DNS information. The zone compiler builds the
precompiled database for the nsd daemon, nsd(8).
There is an alternative zone database builder, written in Perl,
available on request. The zone-compiler use RFC 1034/1035
compliant zonefiles as input.

.SH OPTIONS
.TP
.B \-d \fIdirectory\fB
The working \fIdirectory\fR. Zonec will chdir to this
directory before opening any files for input or output.

.TP
.B \-f \fIdatabase\fR
specify the database to write to. Default is nsd.db in the
working directory.

.TP
.B \-v
turn on verbose mode: enable reporting per 100.000 lines read.
Useful/informative when compiling large and huge zonefiles.

.TP
.B \-p
print the compiled zones before writing them into the database (usefull
for debugging)

.TP
.B zone-list-file
A lists of files containing the zone information in RFC1035 style.

.SH AUTHOR
\fInsd\fR is written by Alexis Yushin (NLnet Labs) with
valuable input and assistance from Jaap Akkerhuis (SIDN),
Daniel Karrenberg and Olaf Kolkman (RIPE-NCC), and Miek
Gieben, Erik Rozendaal, and Ted Lindgreen (NLnet Labs).

.SH "SEE ALSO"
.BR nsd (8),
.BR nsdc (8).

.SH CODE STATUS
The current version, 1.0.0, has beta status. The latest
version can be retrieved from
.br
\fIhttp://www.nlnetlabs.nl/nsd/index.en.html\fR

.SH REPORTING BUGS
Please report bugs to nsd-bugs@nlnetlabs.nl.

.SH COPYRIGHT
Copyright NLnet Labs 2002, BSD License.
