.\" @(#)zonec.8 2002 
.TH zonec 8  "22 Feb 2002"
.SH NAME
zonec \- Zone Compiler
.SH SYNOPSIS
.B zonec
[ \fB\-d\fR ] [ \fB\-v\fR ] [ \fB\-f \fIdatabase\fR ]
.BI zone-list-file

.SH WARNING
\fIzonec\fR is currently ALPHA code. There are still rough edges and
bugs. If you run into them please contact \fInsd-bugs@nlnetlabs.nl\fR.

.SH DESCRIPTION
.B zonec
is the \fIz\fRone \fIc\fRcompiler used in conjunction with \fInsd\fR.

\fInsd\fR works with a machine dependent database with the zone
information. \fIzonec\fR is used to compile a RFC1035 style zone file
into that format.

.SH OPTIONS
.TP
.B \-v
turn on verbose mode: enable reporting per 100.000 lines read.

.TP
.B \-d \fIdirectory\fB
cd to \fIdirectory\fR before doing anything.

.TP
.B \-f \fIdatabase\fR
specify the database to write to. 

.TP
.B zone-list-file
A lists of files containing the zone information in RFC1035 style.

.SH AUTHORS
\fInsd\fR is written by 
Alexis Yushin, Eric Roozendaal, Ted Lindgreen, Miek Gieben (All NLnet
Labs) and Olaf Kolkman, Daniel Karrenberg both from RIPE NCC.

.SH "SEE ALSO"
.BR nsd (8),
.BR nsdc (8).

.SH LATEST CODE
The latest version of \fInsd\fR can always be downloaded from
.br
\fIhttp://www.nlnetlabs.nl/nsd/index.en.html\fR

.SH REPORTING BUGS
Please report bugs to nsd-bugs@nlnetlabs.nl.

.SH COPYRIGHT
Copyright NLnet Labs 2002, BSD License.
