server:
  zonesdir: "."
  xfrdfile: ""
  log-time-iso: yes

# Signed zone created with
## ldns-signzone -f - -i 20260101000000 -e 20940101000000 nsec3_no_space.zone nsec3_no_space|grep -v '[[:space:]]NSEC[[:space:]]' > nsec3_no_space.zone.signed
#
zone:
  name: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc.ddddddddddddddddddddddddddddd"
  zonefile: "nsec3_no_space.zone.signed"

