# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1
	verbosity: 5

pattern:
	name: "member-pattern"
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY

zone:
	name: catalog.tld.
	catalog: consumer
	catalog-member-pattern: "member-pattern"
	zonefile: nsec3_mid_zone.zone
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY
