server:
	logfile: "nsd.log"
	xfrdfile: xfrd.state
	zonesdir: ""
	zonelistfile: "zone.list"
	interface: 127.0.0.1

zone:
	name: victim.
	zonefile: svcb_uint16_wrap.zone
	request-xfr: UDP 127.0.0.1@RANDOM NOKEY
	allow-notify: 127.0.0.1@RANDOM NOKEY
	provide-xfr: 0.0.0.0/0 NOKEY

remote-control:
	control-enable: yes
	control-key-file: "svcb_uint16_wrap.nsd_control.key"
	control-cert-file: "svcb_uint16_wrap.nsd_control.pem"
	server-key-file: "svcb_uint16_wrap.nsd_server.key"
	server-cert-file: "svcb_uint16_wrap.nsd_server.pem"

