# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1
	verbosity: 5

zone:
	name: example.com.
	zonefile: ixfr_stale_oldest.zone
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY
	store-ixfr: yes
	ixfr-size: 10000000
	ixfr-number: 5
