# conf file for test tsig
server:
	logfile: "nsd.log"
	zonesdir: ""
	zonelistfile: "zone.list"
	interface: 127.0.0.1

zone:
	name: example.com.
	zonefile: nsec3_ent_optout.zone
	provide-xfr: 127.0.0.1/0 NOKEY
	provide-xfr: ::1/0 NOKEY
