# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1
	verbosity: 5
	answer-cookie: yes

zone:
	name: example.com.
	zonefile: edns-many-cookies.zone
