# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	verbosity: 5
	interface: 127.0.0.1@PORT
	proxy-protocol-port: PORT
 
zone:
	name: example.com.
	zonefile: proxy_consume_reset.zone
