# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1
	verbosity: 5
	log-time-iso: yes

pattern:
	name: "seczone"
	# same zone contents, from the same file for the zones.
	zonefile: xfr_cross_fail.zone
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY

zone:
	name: example1.com.
	include-pattern: "seczone"

zone:
	name: example2.com.
	include-pattern: "seczone"

zone:
	name: example3.com.
	include-pattern: "seczone"

zone:
	name: example4.com.
	include-pattern: "seczone"

zone:
	name: example5.com.
	include-pattern: "seczone"

zone:
	name: example6.com.
	include-pattern: "seczone"

zone:
	name: example7.com.
	include-pattern: "seczone"

zone:
	name: example8.com.
	include-pattern: "seczone"

zone:
	name: example9.com.
	include-pattern: "seczone"

zone:
	name: example10.com.
	include-pattern: "seczone"
