# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1
	verbosity: 5

remote-control:
	control-enable: yes
	control-interface: NSD_CTRL_PATH

pattern:
	name: "pat"
	zonefile: "%s.zone"
	allow-notify: 127.0.0.1 NOKEY
	provide-xfr: 127.0.0.1 NOKEY
	request-xfr: UDP 127.0.0.1@TESTNS_PORT NOKEY

include: "zones.conf"
