# conf file for nsd
server:
	logfile: "nsd.log"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1
	verbosity: 5

zone:
	name: example.com.
	zonefile: nsec3_ixfr_owner.zone
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY

zone:
	name: example2.com.
	zonefile: nsec3_ixfr_owner.zone2
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY

zone:
	name: example3.com.
	zonefile: nsec3_ixfr_owner.zone3
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY

zone:
	name: example4.com.
	zonefile: nsec3_ixfr_owner.zone4
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
	allow-notify: 127.0.0.1/0 NOKEY
	provide-xfr: 127.0.0.1/0 NOKEY
