server:
  zonesdir: "."
  username: ""
  database: ""
  pidfile: ""
  xfrdfile: ""

## zones are signed like this:
#
# ldns-signzone -nt 0 -i 20260101000000 -e 20940101000000 nsec3_long_dname_overflow.zone-253 nsec3_long_dname_overflow.Kx.+015+17804
# ldns-signzone -nt 0 -i 20260101000000 -e 20940101000000 nsec3_long_dname_overflow.zone-254 nsec3_long_dname_overflow.Ky.+015+17804
# ldns-signzone -nt 0 -i 20260101000000 -e 20940101000000 nsec3_long_dname_overflow.zone-255 nsec3_long_dname_overflow.Kz.+015+17804

zone:
  name: "x"
  zonefile: "nsec3_long_dname_overflow.zone-253.signed"

zone:
  name: "y"
  zonefile: "nsec3_long_dname_overflow.zone-254.signed"

zone:
  name: "z"
  zonefile: "nsec3_long_dname_overflow.zone-255.signed"

