server:
    logfile: "nsd.log"
    xfrdfile: nsd.xfrd.state
    pidfile: nsd.pid
    zonesdir: ""
    interface: 127.0.0.1@PORT1
    interface: 127.0.0.1@PORT2
    proxy-protocol-port: PORT1
    proxy-protocol-port: PORT2
    zonelistfile: "nsd.zone.list"
    tls-service-key: "nsd_server.key"
    tls-service-pem: "nsd_server.pem"
    tls-port: PORT2
    allow-proxy: 10.20.30.0/24

zone:
    name: example.com.
    zonefile: proxy_acl_deny.zone
