server:
    logfile: "nsd.log"
    xfrdfile: report_channel.xfrd.state
    identity: "testserver"
    zonesdir: ""
    zonelistfile: "zone.list"
    interface: 127.0.0.1
    report-channel: agent.example.com
    verbosity: 2

zone:
    name: example.com.
    zonefile: report_channel.zone1

pattern:
	name: "ptrn"
	report-channel: agent.example.org.

pattern:
	name: "ptrn2"
	include-pattern: "ptrn"

zone:
    name: example.org.
    zonefile: report_channel.zone2
    include-pattern: "ptrn2"

zone:
    name: example.net.
    zonefile: report_channel.zone3
    include-pattern: "ptrn2"
    report-channel: agent.example.net


