server:
	zonesdir: ""
	username: ""
	chroot: ""
	logfile: nsd.log
	interface: 127.0.0.1

pattern:
	name: "exists"
	zonefile: "catalog_unknown_group.zone"

zone:
	name: "catalog.invalid"
	zonefile: "catalog_unknown_group.catalog"
	catalog: consumer

