server:
    logfile: "nsd.log"
    xfrdfile: nsd.xfrd.state
    pidfile: nsd.pid
    zonesdir: ""
    interface: 127.0.0.1@PORT1
    zonelistfile: "nsd.zone.list"

zone:
    name: example.com.
    zonefile: dnstap_tls_connect.zone

dnstap:
    dnstap-enable: yes
    dnstap-ip: 127.0.0.1@PORT2
    dnstap-tls: yes
    # correct server name
    #dnstap-tls-server-name: "nsd"
    # correct cert bundle.
    #dnstap-tls-cert-bundle: "nsd_server.pem"
    dnstap-tls-server-name: "nsxd"
    dnstap-tls-cert-bundle: ""
    dnstap-log-auth-query-messages: yes
    dnstap-log-auth-response-messages: yes
