# run soms test for zonec

all: ../../zonec
	../../zonec -v -f test.db test.conf

soa: ../../zonec
	../../zonec -v -f test.db soa.conf

unknown: ../../zonec
	../../zonec -v -f test.db unknown.conf

dnssec: ../../zonec
	../../zonec -v -f test.db dnssec.conf
