# conf file for test ixfr out
server:
	logfile: "/dev/stdout"
	pidfile: "nsd.pid"
	zonesdir: ""
	zonelistfile: "zone.list"
	xfrdfile: "nsd.xfrd"
	interface: 127.0.0.1

remote-control:
	control-enable: yes
	control-interface: 127.0.0.1
	control-port: CTRL_PORT
	server-key-file: "nsd_server.key"
	server-cert-file: "nsd_server.pem"
	control-key-file: "nsd_control.key"
	control-cert-file: "nsd_control.pem"

zone:
	name: example.com.
	zonefile: print_apl.zone
	request-xfr: 127.0.0.1@TESTNS_PORT NOKEY
