server:
	logfile: "nsd.log"
	xfrdfile: xfrd.state
	zonesdir: ""
	zonelistfile: "zone.list"
	interface: 127.0.0.1
	interface: ::1
	verbosity: 4

zone:
	name: example.nl.
	zonefile: acl_range.zone
	provide-xfr: 127.0.0.0/8 NOKEY
	provide-xfr: ::1/8 NOKEY

# Ranges should match big-endian (but not little-endian)
zone:
	name: example.com.
	zonefile: acl_range.zone
	provide-xfr: 126.0.0.0-128.0.0.0 NOKEY
	provide-xfr: ::0-::2:0 NOKEY

zone:
	name: example.net.
	zonefile: acl_range.zone
	provide-xfr: 127.0.0.0&255.255.0.0 NOKEY
	provide-xfr: ::0&ffff:ffff:ffff:: NOKEY

# Ranges should not match big-endian (but match little-endian)
zone:
	name: example.org.
	zonefile: acl_range.zone
	provide-xfr: 10.0.0.0-10.255.255.255 NOKEY
	provide-xfr: ::fd00:0-::fdff:ff NOKEY

