# conf file for test tsig
server:
	logfile: "nsd.log"
	zonesdir: ""
	zonelistfile: "zone.list"
	interface: 127.0.0.1
	xfrdfile: "nsd.xfrd.state"

zone:
	name: example.net
	zonefile: nsec3_short_rrname.zone
	provide-xfr: 127.0.0.1/0 NOKEY
	provide-xfr: ::1/0 NOKEY
